"""empty message

Revision ID: 3fe3b152900f
Revises: 43f97f382d12
Create Date: 2021-10-10 09:53:30.205806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe3b152900f'
down_revision = '43f97f382d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
